version: "3.2"

services:

  nucleus:
    container_name: nucleus
    image: elementaryrobotics/nucleus
    volumes:
      - type: volume
        source: shared
        target: /shared
        volume:
          nocopy: true
    command: ./launch.sh

  realsense:
    container_name: realsense
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: volume
        source: shared
        target: /shared
        volume:
          nocopy: true
      - /dev/:/dev/
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - ".:/code"
    depends_on:
      - "nucleus"
    privileged: true
    command: tail -f /dev/null
    environment:
      DISPLAY: :0
      PYTHONUNBUFFERED: 'TRUE'

  # Debug tool for monitoring streams
  stream-viewer:
    container_name: stream-viewer
    image: elementaryrobotics/element-stream-viewer:latest
    restart: always
    logging:
      options:
        max-size: '1m'
        max-file: '5'
    volumes:
      - type: volume
        source: shared
        target: /shared
        volume:
          nocopy: true
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    environment:
      - "DISPLAY=:0"
      - "QT_X11_NO_MITSHM=1"
    depends_on:
      - "nucleus"

volumes:
  shared:
    driver_opts:
      type: tmpfs
      device: tmpfs
