version: "3.2"

services:

  nucleus:
    image: elementaryrobotics/nucleus
    volumes:
      - type: volume
        source: shared
        target: /shared
        volume:
          nocopy: true
    command: ./launch.sh

  realsense:
    image: elementaryrobotics/element-realsense
    volumes:
      - type: volume
        source: shared
        target: /shared
        volume:
          nocopy: true
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    depends_on:
      - "nucleus"
    privileged: true
    command: tail -f /dev/null
    environment:
      - "DISPLAY=:0"

volumes:
  shared:
    driver_opts:
      type: tmpfs
      device: tmpfs
